data_cfg:
  dataset_name: CASIA-B-Hybrid-smpl
  dataset_root: /media/sqp/SQP_Hard_Disk/200-Dataset/casiab-128-end2end
  dataset_partition: ./datasets/CASIA-B/CASIA-B.json
  num_workers: 0
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: CASIA-B
  cache: false

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 50000
  save_name: SMPLCalibrateGait
  eval_func: evaluate_indoor_dataset
  sampler:
    batch_shuffle: false
    batch_size: 1
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
  #    frames_all_limit: 120 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos euc
  transform:
    - type: BaseSilCuttingTransform
      img_w: 64
    - type: NoOperation

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 0.1
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true
  - loss_term_weight: 1.0
    type: MSELoss
    log_prefix: mse
  - loss_term_weight: 1
    type: FixLoss
    log_prefix: fix_loss

model_cfg:
  model: SMPLCalibrateGait
  backbone_cfg:
    in_channels: 1
    layers_cfg: # Layers configuration for automatically model construction
      - BC-64
      - BC-64
      - M
      - BC-128
      - BC-128
      - M
      - BC-256
      - BC-256
    type: Plain
  SeparateFCs:
    in_channels: 256
    out_channels: 256
    parts_num: 31
  SMPL_SeparateFCs:
    in_channels: 512
    out_channels: 256
    parts_num: 1
  SeparateBNNecks:
    class_num: 74
    in_channels: 256
    parts_num: 31
  bin_num:
    - 16
    - 8
    - 4
    - 2
    - 1
optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 15000
    - 30000
    - 45000

  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  fix_BN: false
  log_iter: 100
  with_test: true
  restore_ckpt_strict: true
  restore_hint: 44000
  save_iter: 1000
  save_name: experiment3
  sync_BN: true
  total_iter: 80000
  sampler:
    batch_shuffle: true
    batch_size:
      - 8
      - 8
    frames_num_fixed: 15 # fixed frames number for training
    frames_num_max: 50 # max frames number for unfixed training
    frames_num_min: 25 # min frames number for unfixed traing
    sample_type: fixed_ordered # fixed control input frames number, unordered for controlling order of input tensor; Other options: unfixed_ordered or all_ordered
    frames_skip_num: 1
    type: TripletSampler
  transform:
    - type: BaseSilCuttingTransform
      img_w: 64
    - type: NoOperation
